version: '3.3'

services:

  mysql-db:
    # 指定容器的名称
    container_name: mysql-xx     
    # 指定镜像和版本
    image: aesoper/mysql:5.7.40                   
    ports:
      - "3306:3306"
    restart: always
    # 容器日志大小配置
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    environment:
      # 配置root密码
      MYSQL_ROOT_PASSWORD: xj2022