name: Build and Push MySQL Image

on:
  push:
    branches: [ main ]
    paths:
      - 5.7/**
  pull_request:
    branches: [ main ]
    paths:
      - 5.7/**
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:5.7"
          platforms: linux/amd64,linux/arm64/v8
          load: true
          push: true
          tags: aesoper/mysql:latest 